language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5

before_script:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then NTESTER_FLAGS="phpdbg --coverage ./coverage.xml --coverage-src ./src/ ./tests/src/"; else NTESTER_FLAGS=""; fi

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true;
      fi

    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

script:
  - ./tests/run-tests $NTESTER_FLAGS
